const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike slim shirt',
      category: 'Shirts',
      image: '/images/member-7.png',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviwes: 10,
      description: 'high quality',
    },
    {
      name: 'Sir Slim shirt',
      slug: 'sir slim shirt',
      category: 'Shirts',
      image: '/images/photo1.png',
      price: 300,
      countInStock: 20,
      brand: 'Nike',
      rating: 5,
      numReviwes: 15,
      description: 'high quality',
    },
    {
      name: 'Vip Slim shirt',
      slug: 'vip slim shirt',
      category: 'Shirts',
      image: '/images/photo2.png',
      price: 100,
      countInStock: 5,
      brand: 'Nike',
      rating: 4,
      numReviwes: 5,
      description: 'high quality',
    },
    {
      name: 'Adi Slim shirt',
      slug: 'adi slim shirt',
      category: 'Shirts',
      image: '/images/photo3.png',
      price: 70,
      countInStock: 115,
      brand: 'Adi',
      rating: 34.5,
      numReviwes: 2,
      description: 'high quality',
    },
  ],
};
export default data;
